#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "board.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  position startPos = { 0, 0 };
  tetrimino activeTetrimino = newTetrimino(TETRIMINO_Z, startPos);

  drawBoard();
  
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    waitForVBlank();
    
    clearTetrimino(activeTetrimino);
    if (KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
        activeTetrimino.pos.x--;
    }
    if (KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
        activeTetrimino.pos.x++;
    }
    if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
        activeTetrimino.state--;
        if (activeTetrimino.state == -1) {
            activeTetrimino.state = 3;
        }
    }
    if (KEY_JUST_PRESSED(BUTTON_B, currentButtons, previousButtons)) {
        activeTetrimino.state++;
        if (activeTetrimino.state == 4) {
            activeTetrimino.state = 0;
        }
    }
    if (vBlankCounter != 0 && vBlankCounter % 60 == 0) {
        activeTetrimino.pos.y++;
    }
    drawTetrimino(activeTetrimino);
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:

        // state = ?
        break;
      case PLAY:

        // state = ?
        break;
      case WIN:

        // state = ?
        break;
      case LOSE:

        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
